### ISSUE TITLE
Add Kms or gles support for pi 4

### ISSUE THREAD

**Issue by saitoh00** [mickelson/attract#603] opened 2020-03-03 00:46 UTC
Hello, its needed these support for use it in raspberry pi 4 without x11, example : launch from retropie or include it.

**Comment by kwyxz** [comment] 2020-04-29 18:18
Duplicate of #575

**Comment by fczuardi** [comment] 2020-05-15 12:28
Well, after https://github.com/mickelson/attract/issues/575#issuecomment-622987074 it looks like this is not a duplicate anymore, due to a bad title on #575

**Comment by kwyxz** [comment] 2020-06-04 20:17
My bad : duplicate of #576

**Closed** 2020-06-16 20:00 UTC
