### ISSUE TITLE
attract.exe does not work in Windows 10 64-bit

### ISSUE THREAD

**Issue by DJRM2021** [mickelson/attract#686] opened 2021-07-15 02:36 UTC
attract.exe does not work in Windows 10 pro 64-bit.
ver. 2.6.1.
Windows 10.0.19043 Build 19043
16GB RAM, intel i5-1135G7 11th gen

attract --loglevel debug
last_run.log:
_Attract-Mode v2.6.1 (Windows, SFML 2.5.1 +SWF +7z +Curl) 
avcodec 58.54.100 / avformat 58.29.100 / swscale 5.5.100 / avutil 56.31.100 / swresample 3.5.100

NvAPI: nvapi64.dll loaded_

Basically, double-clicking attract.exe doesn't open up or start the attractmode main window; Nothing happens.
Trying to run it via command line; Nothing happens.

**Comment by oomek** [comment] 2021-07-15 02:40
Duplicate of https://github.com/mickelson/attract/issues/663

**Closed by oomek** 2021-07-15 02:40 UTC

**Comment by DJRM2021** [comment] 2021-07-19 14:06
Hi, where can I get the nightly build that contains commit # b0d5424? Thanks.

**Comment by oomek** [comment] 2021-07-19 14:25
http://forum.attractmode.org/index.php?topic=2324.0

**Comment by DJRM2021** [comment] 2021-07-20 02:23
Sorry but...
![image](https://user-images.githubusercontent.com/77593544/126252480-076280a7-3cc2-4bb5-91a3-84e833a32e33.png)
Also, when trying to right click > Save Link as... in Google Chrome, does not work.

**Comment by oomek** [comment] 2021-07-20 02:33
Works here. Must be your firewall or internet provider.

**Comment by DJRM2021** [comment] 2021-07-20 03:29
Thank you! Hoping for a new release. Have a good day.
