### ISSUE TITLE
Can't update Minimum Run Time value

### ISSUE THREAD

**Issue by vthyng** [mickelson/attract#256] opened 2016-07-27 04:49 UTC
When I select Minimum Run Time and hit enter, it changes to edit mode.  I can delete the value, but no keys I press will result in a number appearing.  Escape brings me back out of edit mode, showing the default value 0 again.  Using latest floob image on RPi3.  As a work around, I manually enter 10 in the .attract/emulators/mama (Mame4all).cfg file.  I made a guess of minimum_run_time and the value is showing up.  However attract is still running in the background after I launch a game in mame.

**Comment by mickelson** [comment] 2018-08-14 04:44
feature has been significantly reworked and can't reproduce, so closing for now

**Closed by mickelson** 2018-08-14 04:44 UTC
