### ISSUE TITLE
Asynchronous image loading to aid HDD bottlenecking

### ISSUE THREAD

**Issue by oomek** [mickelson/attract#342] opened 2017-04-14 16:57 UTC
Have you ever considered a possibility of using async method on loadFromFile() or asynchronously load an image to memory and then call loadFromMemory() function? 

In the current state Attract Mode is choking on fast updating artworks. When they are loadded from HDD the animations are freezing until reading finishes. Using SSD helps, but not everyone can afford one with a decent capacity.

**Comment by cosmicdan** [comment] 2017-04-16 20:03
You seem to know what you're talking about - why not try it yourself and make a PR? ;)

I would try it, but I'm barely a code hacker when it comes to C(++). I wouldn't even know how to store the images in memory (creating some kind of ArrayList equivalent), let alone how to handle the buffer sizes (we obviously don't want to load EVERY image into memory, but rather the next/previous n amount), etc...

**Comment by oomek** [comment] 2017-04-16 20:45
You do not to have all the images stored in memory. It's just a matter to handle the image loading asynchronously to the main thread. SFML is not multithreaded, but It can be done in 2 ways. You create a separate thread which loads an image to the buffer, or you call async to load it in a lambda expression. Once you've checked it's done loading in the main thread you can load the texture from memory the normal way and it will be without any delay. I've tried async few day ago, but since textures in AM are not static objects I've had some compiler errors. I'm not a guru in c++ either, but I can try the multithreaded method later. You do not to worry about the memory buffers management as it done automatically, as long as you load a whole png to memory, not just a raw bitmap you just pass the &buffer[0] and buffer.size() to the loadFromMemory() function and it decodes automatically.

**Comment by popoklo** [comment] 2017-06-12 21:43
i think this is a very important thing for AM, I stopped directly working on theme because of massive HDD loading for rapid fileloading.

**Comment by mickelson** [comment] 2020-06-13 23:17
Closing as a duplicate of https://github.com/mickelson/attract/issues/179

**Closed by mickelson** 2020-06-13 23:17 UTC
