### ISSUE TITLE
Configured sounds not playing (Up, Down, Left, Right)

### ISSUE THREAD

**Issue by OzFalcon** [mickelson/attract#555] opened 2019-04-05 23:31 UTC
Attract Mode V2.5.1 running on Linux.
Some configured sound files are not playing.
Event sound files for Up, Down, Left, Right are not playing.
But other events (Select, Previous/Next Page, Previous/Next Game) are working.

"--loglevel debug" Doesn't seem to show any problems regarding config.

> Command intercepted by script handler: right
> Command intercepted by script handler: left
> Command intercepted by script handler: down
> [Transition] type=EndNavigation, var=0
> Command intercepted by script handler: up
> [Transition] type=EndNavigation, var=0

I am using the Grid layout with some minor aesthetic changes but nothing that should alter standard operation.
![Configure_Sound](https://user-images.githubusercontent.com/13824723/55661305-dd9d0e00-5856-11e9-9670-5468c6b6e356.png)
![Simple_Grid](https://user-images.githubusercontent.com/13824723/55661312-ec83c080-5856-11e9-92ed-a39f2c88a193.png)

**Comment by randombyt** [comment] 2019-04-11 04:43
If you are using "fe.get_input_state" function then direction keys will only affect keyboard input not gamepad inputs (which will be in this format "Joy0 Down").

**Comment by zpaolo11x** [comment] 2019-04-12 06:27
> If you are using "fe.get_input_state" function then direction keys will only affect keyboard input not gamepad inputs (which will be in this format "Joy0 Down").

Good to know, what if I have a signal callback routine and I attach sounds to the "left" "right" events? Will it work with a joypad / joystick too? (I don't have one to test :( )

**Comment by OzFalcon** [comment] 2019-04-12 14:18
I'm using a stripped down grid layout.
The grid layout doesn't use "fe.get_input_state" looking at the layout.nut file.
For input there is only keyboard - A standard I-Pac device. I havn't tried a Joystick/Gamepad.
Attached is the Grid Runner layout nut file for reference.
It still needs the frame.png found in Grid layout to operate.
[layout.nut.txt](https://github.com/mickelson/attract/files/3073662/layout.nut.txt)

**Comment by zpaolo11x** [comment] 2019-04-12 15:18
Some things I'll try: the same audio file that doesn't play when attached to left/right etc is working if attached to other events like "esc" or "back"? Other sound files work if attached to left/right etc? Last but not least, does it work in any other layout?

**Comment by OzFalcon** [comment] 2019-04-12 23:07
Yes, The audio file works with other events.
I havn't tried with other layouts as yet, But will have a poke around this weekend and learn a little more on how things operate.

**Comment by OzFalcon** [comment] 2019-04-12 23:51
Ok, I think I have it working in some fashion.

Standard movement within the layout uses function "update_frame" to position with.
No events are actually called from within this function.
```
	function update_frame()
	{
		frame.x = width * sel_x;
		frame.y = fe.layout.height / 24 + height * sel_y;
		
		name_t.index_offset = num_t.index_offset = get_sel() - selection_index;	
	}
```

To enable sound a "custom1" signal is configured to the audio file and called either before or within the "update_frame" function.
```
		switch ( sig )	
		{
		case "up":
			if ( sel_y > 0 )
			{
				sel_y--;
				fe.signal( "custom1" );
				update_frame();
			}
```

I'm still not sure if this is the "Correct" way to do it, But it does work.

**Comment by randombyt** [comment] 2019-04-15 07:40
> 
> 
> > If you are using "fe.get_input_state" function then direction keys will only affect keyboard input not gamepad inputs (which will be in this format "Joy0 Down").
> 
> Good to know, what if I have a signal callback routine and I attach sounds to the "left" "right" events? Will it work with a joypad / joystick too? (I don't have one to test :( )

Signal callback works as intended with both keyboard and gamepad. AFAIK only Input_state differs between keyboard input (i.e. "Down") and gamepad input (i.e. "Joy0 Down").

**Closed** 2019-05-18 06:25 UTC
