### ISSUE TITLE
Windows 10 20H2 Doesn't boot 

### ISSUE THREAD

**Issue by Sherm1984** [mickelson/attract#680] opened 2021-04-06 10:43 UTC
[last_run.log](https://github.com/mickelson/attract/files/6264007/last_run.log)

Using the same fresh copy on version 1909 works but the latest version doesn't boot.

**Comment by sergiohf** [comment] 2021-04-06 15:19
> [last_run.log](https://github.com/mickelson/attract/files/6264007/last_run.log)
> 
> Using the same fresh copy on version 1909 works but the latest version doesn't boot.

I have the exact same problem on my windows 10 20H2
Nvidia GTX1050
Intel core i5

**Comment by oomek** [comment] 2021-04-06 15:21
Please provide a full log
`attract.exe --loglevel debug`

**Comment by sergiohf** [comment] 2021-04-06 15:27
Thats real strange, doing through cmd attract.exe --loglevel debug start the AM normally
[last_run.log](https://github.com/mickelson/attract/files/6265775/last_run.log)

**Comment by sergiohf** [comment] 2021-04-06 15:36
> Thats real strange, doing through cmd attract.exe --loglevel debug start the AM normally
> [last_run.log](https://github.com/mickelson/attract/files/6265775/last_run.log)
I past the last 2 hours trying to start AM, restarted the system, try a new install of AM and nothing. 

Now its working normally. I even restarted the system and continue to work.

**Comment by Sherm1984** [comment] 2021-04-06 15:52
[last_run.log](https://github.com/mickelson/attract/files/6265955/last_run.log)

this is all get?

**Comment by oomek** [comment] 2021-04-06 15:59
Duplicate of https://github.com/mickelson/attract/issues/663

Please use the daily build

**Closed by oomek** 2021-04-06 15:59 UTC

**Comment by andersstorhaug** [comment] 2021-04-26 21:30
Here's a workaround for v2.6.1: in the NVIDIA control panel, turn off "Shader Cache" for `attract.exe`.

**Comment by oomek** [comment] 2021-04-26 21:37
It has nothing to do with the shader cache. Please do not share workarounds that are incorrect. You just created a driver profile which for some unknown reasons x64 build of Attract Mode failed to create when an OpenGL context already active. This issue was fixed, so please use the latest daily build as advised multiple times.

**Comment by andersstorhaug** [comment] 2021-04-26 21:43
> It has nothing to do with the shader cache. Please do not share workarounds that are incorrect. You just created a driver profile which for some unknown reasons x64 build of Attract Mode failed to create when an OpenGL context already active. This issue was fixed, so please use the latest daily build as advised multiple times.

Strange. Deleted my comment.
