### ISSUE TITLE
Request: Vid.ImagesOnly support for multiple directories

### ISSUE THREAD

**Issue by chris-vg** [mickelson/attract#200] opened 2016-03-23 02:22 UTC
Correct me if i'm wrong, but it appears that currently when the `Vid.ImagesOnly` flag is set on an artwork object, it appears to only search the first directory in the list.

So, if I have multiple directories set up for "snap" artwork (eg d:\mame\videos;d:\mame\snap), i then add the code:

`local snap = fe.add_artwork("snap", 0, 0, 640, 480);`
`snap.video_flags = Vid.ImagesOnly;`

AM will not display the snap because it couldn't find any images (only videos) in the first directory (d:\mame\videos).

Would it be possible to add logic to scan the next directory in the array if the current one has no match?

**Comment by mickelson** [comment] 2016-04-14 06:40
Yes, this was not working as intended.  It should be fixed now, thanks.

**Closed by mickelson** 2016-04-14 06:40 UTC
