### ISSUE TITLE
Multi-Monitor Setup: Frontend coveres all monitors

### ISSUE THREAD

**Issue by Onkel-Tom** [mickelson/attract#128] opened 2015-05-13 12:57 UTC
If i run AM in a multi-monitor setuo (e.g. a Laptop with a monitor attached), the UI coveres on the one hand side more than monitor 1 (i.e. it is larger than to fit on monitor 1) but the "rest" is not visible on monitor 2, though.
Basically, a resolution is choosen which doesn't fit on monitor 1 but isn't extended to monitor 2 at the same time.
Resolution: a screen resolution should be picked which matches the resolution of monitor 1
OS is Win8, Desktop is set to "extend" mode
Thanks, Thomas

**Comment by liquid8d** [comment] 2015-05-22 05:12
Just an fyi, this is apparently a bug with multiple monitors on the current windows build..
http://forum.attractmode.org/index.php?topic=187.msg1177#msg1177

**Comment by Onkel-Tom** [comment] 2015-05-22 06:32
OK, thanks for letting me know.
I'll be patient...

2015-05-22 7:12 GMT+02:00 liquid8d <notifications@github.com>:

**Comment by mickelson** [comment] 2015-05-23 07:24
Thanks for the report.  This should be fixed now in the version posted here: https://github.com/mickelson/attract/releases/tag/v1.5.3

Please let me know if you have any issues still.

**Comment by liquid8d** [comment] 2015-05-23 15:00
It still stretches across both monitors for me with this release. I tried both Fill Screen and Fullscreen mode.

**Comment by liquid8d** [comment] 2015-05-23 15:31
Just a quick note. If you switch to Window mode, I think the concern the original submitter mentioned is still there..  Monitor 1 display overlaps slightly into monitor 2 - as much as the width of the Window border it seems.

Here's an example:
http://postimg.org/image/71hnidp39/

Strangely, the screenshot makes it appear fine since the taskbar matches the width of monitor 1 content.. but probably the length of the windows left and right borders in pixels overlaps onto monitor 2.

Obviously not a huge issue - can't imagine many will run AM in Window mode on multiple monitors :) 

Nevertheless, the window border width in Windows + Window mode might be something that needs to be considered in code when dealing with resolutions/display.

**Comment by djvj1** [comment] 2015-05-29 04:56
64-bit version is not fixed. 32-bit version works fine.

**Comment by mickelson** [comment] 2015-06-10 06:31
Ok yes, I can reproduce this on the 64-bit build for windows.  Works fine on the 32-bit version.  I'm currently stumped as to why.

**Comment by liquid8d** [comment] 2015-06-14 05:00
Just to make life more difficult for you - the 32bit one still spans across both screens when you switch to window mode :) Not a huge deal but an FYI.

**Comment by nilsbyte** [comment] 2015-09-26 10:12
![img_5109](https://cloud.githubusercontent.com/assets/6209727/10117008/d62782ec-6447-11e5-9c72-63900d237d6e.JPG)

Not fixed in 32-bit and 64-bit version. please reopen issue.

**Comment by mickelson** [comment] 2015-09-26 14:45
oh no! thanks for the report, I will look into this. what a pain this has become...

**Comment by liquid8d** [comment] 2015-09-26 18:44
I assume you are on Windows? Also note - did you try both 32bit and 64bit and are you using Fill Screen or Full Screen. I haven't checked this on my multi-monitor setup recently, I'll need to try again.

**Comment by Aergan** [comment] 2015-10-04 19:51
Having the same issue in a multi-monitor setup on Windows 10 x64. Affects both 32 and 64bit versions.

**Comment by Dark574** [comment] 2016-08-18 17:56
I have also this issue...
I am using Linux Manjaro in a Multi-Monitor setup. Affects the package from the official repository (Version 2.1.0-1)

Multi-Monitor disabled
Fill screen = Shows leftmost display with task bar (ok so far) but the problem is that the content is cut up, like its trying to display it on both monitors...so i see only just part of Attract Mode Screen
Full screen = Same as Fill Screen
Window = Same as Fill Screen, just in a window

Multi-Monitor activated
Fill screen = shows content on the leftmost display without error and right screen is black
Full screen = shows on leftmost display, but ccontent is squeezed in half on the left side of the screen :/
Window = shows content on leftmos display without error and with taskbar...working correctly

the only setting i can use ist MultiMonitor with Window Mode

**Closed** 2018-08-14 03:41 UTC
