### ISSUE TITLE
compiling in ubuntu gives warnings

### ISSUE THREAD

**Issue by enzof6** [mickelson/attract#404] opened 2018-01-05 23:03 UTC
the following warnings are throwing up when compiling on Ubuntu 16.04 

arcade@arcade-HP:~/attractMode_sources$ make
flags: -Wl,--export-dynamic -I/usr/include/freetype2 -DDATA_PATH=\"/usr/local/share/attract/\" -O2 -DNDEBUG -Iextlibs/miniz -Iextlibs/audio/include -D__STDC_CONSTANT_MACROS -I/usr/include/freetype2 -I/home/arcade/ffmpeg_build/include -I/usr/include/AL -I/home/arcade/ffmpeg_build/include -Iextlibs/squirrel/include -Iextlibs/sqrat/include -Iextlibs/gameswf  -DUSE_XLIB -DUSE_XINERAMA -DUSE_FONTCONFIG -DUSE_SWRESAMPLE
fatal: Not a git repository (or any of the parent directories): .git
Compiling obj/fe_base.o...
In file included from /usr/include/c++/5/backward/hash_map:60:0,
                 from extlibs/gameswf/base/container.h:75,
                 from extlibs/gameswf/base/image.h:14,
                 from extlibs/gameswf/gameswf/gameswf.h:21,
                 from src/fe_base.cpp:34:
/usr/include/c++/5/backward/backward_warning.h:32:2: warning: #warning This file includes at least one deprecated or antiquated header which may be removed without further notice at a future date. Please use a non-deprecated interface with equivalent functionality instead. For a listing of replacement headers and interfaces, consult the file backward_warning.h. To disable this warning use -Wno-deprecated. [-Wcpp]
 #warning \
  ^
Compiling obj/fe_util.o...
Compiling obj/fe_util_sq.o...
Compiling obj/fe_cmdline.o...
Compiling obj/fe_info.o...
Compiling obj/fe_input.o...
Compiling obj/fe_romlist.o...
Compiling obj/fe_settings.o...
Compiling obj/scraper_xml.o...
Compiling obj/scraper_general.o...
Compiling obj/scraper_net.o...
Compiling obj/fe_config.o...
Compiling obj/fe_presentable.o...
Compiling obj/fe_present.o...
Compiling obj/sprite.o...
Compiling obj/fe_image.o...
Compiling obj/fe_sound.o...
Compiling obj/fe_shader.o...
Compiling obj/fe_overlay.o...
Compiling obj/fe_window.o...
Compiling obj/tp.o...
Compiling obj/fe_text.o...
Compiling obj/fe_listbox.o...
Compiling obj/fe_vm.o...
Compiling obj/zip.o...
Compiling obj/main.o...
Compiling obj/fe_net.o...
Compiling obj/swf.o...
In file included from /usr/include/c++/5/backward/hash_map:60:0,
                 from extlibs/gameswf/base/container.h:75,
                 from extlibs/gameswf/base/tu_file.h:18,
                 from src/swf.cpp:26:
/usr/include/c++/5/backward/backward_warning.h:32:2: warning: #warning This file includes at least one deprecated or antiquated header which may be removed without further notice at a future date. Please use a non-deprecated interface with equivalent functionality instead. For a listing of replacement headers and interfaces, consult the file backward_warning.h. To disable this warning use -Wno-deprecated. [-Wcpp]
 #warning \
  ^
Compiling obj/media.o...
src/media.cpp: In member function ‘void FeVideoImp::preload()’:
src/media.cpp:534:15: warning: ‘AVCodecContext::refcounted_frames’ is deprecated [-Wdeprecated-declarations]
    codec_ctx->refcounted_frames = 1;
               ^
In file included from src/media.cpp:31:0:
/home/arcade/ffmpeg_build/include/libavcodec/avcodec.h:2328:9: note: declared here
     int refcounted_frames;
         ^
src/media.cpp:534:15: warning: ‘AVCodecContext::refcounted_frames’ is deprecated [-Wdeprecated-declarations]
    codec_ctx->refcounted_frames = 1;
               ^
In file included from src/media.cpp:31:0:
/home/arcade/ffmpeg_build/include/libavcodec/avcodec.h:2328:9: note: declared here
     int refcounted_frames;
         ^
src/media.cpp:534:15: warning: ‘AVCodecContext::refcounted_frames’ is deprecated [-Wdeprecated-declarations]
    codec_ctx->refcounted_frames = 1;
               ^
In file included from src/media.cpp:31:0:
/home/arcade/ffmpeg_build/include/libavcodec/avcodec.h:2328:9: note: declared here
     int refcounted_frames;
         ^
src/media.cpp:539:14: warning: ‘int avcodec_decode_video2(AVCodecContext*, AVFrame*, int*, const AVPacket*)’ is deprecated [-Wdeprecated-declarations]
    int len = avcodec_decode_video2( codec_ctx, raw_frame,
              ^
In file included from src/media.cpp:31:0:
/home/arcade/ffmpeg_build/include/libavcodec/avcodec.h:4664:5: note: declared here
 int avcodec_decode_video2(AVCodecContext *avctx, AVFrame *picture,
     ^
src/media.cpp:539:14: warning: ‘int avcodec_decode_video2(AVCodecContext*, AVFrame*, int*, const AVPacket*)’ is deprecated [-Wdeprecated-declarations]
    int len = avcodec_decode_video2( codec_ctx, raw_frame,
              ^
In file included from src/media.cpp:31:0:
/home/arcade/ffmpeg_build/include/libavcodec/avcodec.h:4664:5: note: declared here
 int avcodec_decode_video2(AVCodecContext *avctx, AVFrame *picture,
     ^
src/media.cpp:540:24: warning: ‘int avcodec_decode_video2(AVCodecContext*, AVFrame*, int*, const AVPacket*)’ is deprecated [-Wdeprecated-declarations]
     &got_frame, packet );
                        ^
In file included from src/media.cpp:31:0:
/home/arcade/ffmpeg_build/include/libavcodec/avcodec.h:4664:5: note: declared here
 int avcodec_decode_video2(AVCodecContext *avctx, AVFrame *picture,
     ^
src/media.cpp: In member function ‘void FeVideoImp::video_thread()’:
src/media.cpp:706:17: warning: ‘AVCodecContext::refcounted_frames’ is deprecated [-Wdeprecated-declarations]
      codec_ctx->refcounted_frames = 1;
                 ^
In file included from src/media.cpp:31:0:
/home/arcade/ffmpeg_build/include/libavcodec/avcodec.h:2328:9: note: declared here
     int refcounted_frames;
         ^
src/media.cpp:706:17: warning: ‘AVCodecContext::refcounted_frames’ is deprecated [-Wdeprecated-declarations]
      codec_ctx->refcounted_frames = 1;
                 ^
In file included from src/media.cpp:31:0:
/home/arcade/ffmpeg_build/include/libavcodec/avcodec.h:2328:9: note: declared here
     int refcounted_frames;
         ^
src/media.cpp:706:17: warning: ‘AVCodecContext::refcounted_frames’ is deprecated [-Wdeprecated-declarations]
      codec_ctx->refcounted_frames = 1;
                 ^
In file included from src/media.cpp:31:0:
/home/arcade/ffmpeg_build/include/libavcodec/avcodec.h:2328:9: note: declared here
     int refcounted_frames;
         ^
src/media.cpp:711:16: warning: ‘int avcodec_decode_video2(AVCodecContext*, AVFrame*, int*, const AVPacket*)’ is deprecated [-Wdeprecated-declarations]
      int len = avcodec_decode_video2( codec_ctx, raw_frame,
                ^
In file included from src/media.cpp:31:0:
/home/arcade/ffmpeg_build/include/libavcodec/avcodec.h:4664:5: note: declared here
 int avcodec_decode_video2(AVCodecContext *avctx, AVFrame *picture,
     ^
src/media.cpp:711:16: warning: ‘int avcodec_decode_video2(AVCodecContext*, AVFrame*, int*, const AVPacket*)’ is deprecated [-Wdeprecated-declarations]
      int len = avcodec_decode_video2( codec_ctx, raw_frame,
                ^
In file included from src/media.cpp:31:0:
/home/arcade/ffmpeg_build/include/libavcodec/avcodec.h:4664:5: note: declared here
 int avcodec_decode_video2(AVCodecContext *avctx, AVFrame *picture,
     ^
src/media.cpp:712:27: warning: ‘int avcodec_decode_video2(AVCodecContext*, AVFrame*, int*, const AVPacket*)’ is deprecated [-Wdeprecated-declarations]
        &got_frame, packet );
                           ^
In file included from src/media.cpp:31:0:
/home/arcade/ffmpeg_build/include/libavcodec/avcodec.h:4664:5: note: declared here
 int avcodec_decode_video2(AVCodecContext *avctx, AVFrame *picture,
     ^
src/media.cpp:718:35: warning: ‘AVFrame::pkt_pts’ is deprecated [-Wdeprecated-declarations]
       raw_frame->pts = raw_frame->pkt_pts;
                                   ^
In file included from /home/arcade/ffmpeg_build/include/libavcodec/avcodec.h:38:0,
                 from src/media.cpp:31:
/home/arcade/ffmpeg_build/include/libavutil/frame.h:302:13: note: declared here
     int64_t pkt_pts;
             ^
src/media.cpp:718:35: warning: ‘AVFrame::pkt_pts’ is deprecated [-Wdeprecated-declarations]
       raw_frame->pts = raw_frame->pkt_pts;
                                   ^
In file included from /home/arcade/ffmpeg_build/include/libavcodec/avcodec.h:38:0,
                 from src/media.cpp:31:
/home/arcade/ffmpeg_build/include/libavutil/frame.h:302:13: note: declared here
     int64_t pkt_pts;
             ^
src/media.cpp:718:35: warning: ‘AVFrame::pkt_pts’ is deprecated [-Wdeprecated-declarations]
       raw_frame->pts = raw_frame->pkt_pts;
                                   ^
In file included from /home/arcade/ffmpeg_build/include/libavcodec/avcodec.h:38:0,
                 from src/media.cpp:31:
/home/arcade/ffmpeg_build/include/libavutil/frame.h:302:13: note: declared here
     int64_t pkt_pts;
             ^
src/media.cpp: In member function ‘bool FeMedia::internal_open(sf::Texture*)’:
src/media.cpp:1020:73: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
    AVCodecContext *codec_ctx = m_imp->m_format_ctx->streams[stream_id]->codec;
                                                                         ^
In file included from src/media.cpp:32:0:
/home/arcade/ffmpeg_build/include/libavformat/avformat.h:876:21: note: declared here
     AVCodecContext *codec;
                     ^
src/media.cpp:1020:73: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
    AVCodecContext *codec_ctx = m_imp->m_format_ctx->streams[stream_id]->codec;
                                                                         ^
In file included from src/media.cpp:32:0:
/home/arcade/ffmpeg_build/include/libavformat/avformat.h:876:21: note: declared here
     AVCodecContext *codec;
                     ^
src/media.cpp:1020:73: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
    AVCodecContext *codec_ctx = m_imp->m_format_ctx->streams[stream_id]->codec;
                                                                         ^
In file included from src/media.cpp:32:0:
/home/arcade/ffmpeg_build/include/libavformat/avformat.h:876:21: note: declared here
     AVCodecContext *codec;
                     ^
src/media.cpp:1075:73: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
    AVCodecContext *codec_ctx = m_imp->m_format_ctx->streams[stream_id]->codec;
                                                                         ^
In file included from src/media.cpp:32:0:
/home/arcade/ffmpeg_build/include/libavformat/avformat.h:876:21: note: declared here
     AVCodecContext *codec;
                     ^
src/media.cpp:1075:73: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
    AVCodecContext *codec_ctx = m_imp->m_format_ctx->streams[stream_id]->codec;
                                                                         ^
In file included from src/media.cpp:32:0:
/home/arcade/ffmpeg_build/include/libavformat/avformat.h:876:21: note: declared here
     AVCodecContext *codec;
                     ^
src/media.cpp:1075:73: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
    AVCodecContext *codec_ctx = m_imp->m_format_ctx->streams[stream_id]->codec;
                                                                         ^
In file included from src/media.cpp:32:0:
/home/arcade/ffmpeg_build/include/libavformat/avformat.h:876:21: note: declared here
     AVCodecContext *codec;
                     ^
src/media.cpp: In member function ‘virtual bool FeMedia::onGetData(sf::SoundStream::Chunk&)’:
src/media.cpp:1232:23: warning: ‘AVCodecContext::refcounted_frames’ is deprecated [-Wdeprecated-declarations]
   m_audio->codec_ctx->refcounted_frames = 1;
                       ^
In file included from src/media.cpp:31:0:
/home/arcade/ffmpeg_build/include/libavcodec/avcodec.h:2328:9: note: declared here
     int refcounted_frames;
         ^
src/media.cpp:1232:23: warning: ‘AVCodecContext::refcounted_frames’ is deprecated [-Wdeprecated-declarations]
   m_audio->codec_ctx->refcounted_frames = 1;
                       ^
In file included from src/media.cpp:31:0:
/home/arcade/ffmpeg_build/include/libavcodec/avcodec.h:2328:9: note: declared here
     int refcounted_frames;
         ^
src/media.cpp:1232:23: warning: ‘AVCodecContext::refcounted_frames’ is deprecated [-Wdeprecated-declarations]
   m_audio->codec_ctx->refcounted_frames = 1;
                       ^
In file included from src/media.cpp:31:0:
/home/arcade/ffmpeg_build/include/libavcodec/avcodec.h:2328:9: note: declared here
     int refcounted_frames;
         ^
src/media.cpp:1241:13: warning: ‘int avcodec_decode_audio4(AVCodecContext*, AVFrame*, int*, const AVPacket*)’ is deprecated [-Wdeprecated-declarations]
   int len = avcodec_decode_audio4( m_audio->codec_ctx, frame, &got_frame, packe
             ^
In file included from src/media.cpp:31:0:
/home/arcade/ffmpeg_build/include/libavcodec/avcodec.h:4615:5: note: declared here
 int avcodec_decode_audio4(AVCodecContext *avctx, AVFrame *frame,
     ^
src/media.cpp:1241:13: warning: ‘int avcodec_decode_audio4(AVCodecContext*, AVFrame*, int*, const AVPacket*)’ is deprecated [-Wdeprecated-declarations]
   int len = avcodec_decode_audio4( m_audio->codec_ctx, frame, &got_frame, packe
             ^
In file included from src/media.cpp:31:0:
/home/arcade/ffmpeg_build/include/libavcodec/avcodec.h:4615:5: note: declared here
 int avcodec_decode_audio4(AVCodecContext *avctx, AVFrame *frame,
     ^
src/media.cpp:1241:82: warning: ‘int avcodec_decode_audio4(AVCodecContext*, AVFrame*, int*, const AVPacket*)’ is deprecated [-Wdeprecated-declarations]
 t len = avcodec_decode_audio4( m_audio->codec_ctx, frame, &got_frame, packet );
                                                                              ^
In file included from src/media.cpp:31:0:
/home/arcade/ffmpeg_build/include/libavcodec/avcodec.h:4615:5: note: declared here
 int avcodec_decode_audio4(AVCodecContext *avctx, AVFrame *frame,
     ^
Compiling obj/squirrel/sqapi.o...
Compiling obj/squirrel/sqbaselib.o...
Compiling obj/squirrel/sqfuncstate.o...
Compiling obj/squirrel/sqdebug.o...
Compiling obj/squirrel/sqlexer.o...
Compiling obj/squirrel/sqobject.o...
Compiling obj/squirrel/sqcompiler.o...
Compiling obj/squirrel/sqstate.o...
Compiling obj/squirrel/sqtable.o...
Compiling obj/squirrel/sqmem.o...
Compiling obj/squirrel/sqvm.o...
Compiling obj/squirrel/sqclass.o...
Archiving obj/libsquirrel.a...
Compiling obj/sqstdlib/sqstdblob.o...
Compiling obj/sqstdlib/sqstdio.o...
Compiling obj/sqstdlib/sqstdstream.o...
Compiling obj/sqstdlib/sqstdmath.o...
Compiling obj/sqstdlib/sqstdstring.o...
Compiling obj/sqstdlib/sqstdaux.o...
Compiling obj/sqstdlib/sqstdsystem.o...
Compiling obj/sqstdlib/sqstdrex.o...
Archiving obj/libsqstdlib.a...
Compiling obj/gsbaselib/configvars.o...
Compiling obj/gsbaselib/ear_clip_triangulate_float.o...
Compiling obj/gsbaselib/ear_clip_triangulate_sint16.o...
Compiling obj/gsbaselib/container.o...
Compiling obj/gsbaselib/file_util.o...
Compiling obj/gsbaselib/image.o...
Compiling obj/gsbaselib/image_filters.o...
Compiling obj/gsbaselib/jpeg.o...
Compiling obj/gsbaselib/logger.o...
Compiling obj/gsbaselib/membuf.o...
Compiling obj/gsbaselib/postscript.o...
Compiling obj/gsbaselib/triangulate_float.o...
Compiling obj/gsbaselib/triangulate_sint32.o...
Compiling obj/gsbaselib/tu_file.o...
Compiling obj/gsbaselib/tu_gc_singlethreaded_marksweep.o...
Compiling obj/gsbaselib/tu_loadlib.o...
Compiling obj/gsbaselib/tu_random.o...
Compiling obj/gsbaselib/tu_timer.o...
Compiling obj/gsbaselib/tu_types.o...
Compiling obj/gsbaselib/utf8.o...
Compiling obj/gsbaselib/utility.o...
Compiling obj/gsbaselib/zlib_adapter.o...
Compiling obj/gameswflib/gameswf_as_classes/as_array.o...
Compiling obj/gameswflib/gameswf_as_classes/as_boolean.o...
Compiling obj/gameswflib/gameswf_as_classes/as_broadcaster.o...
Compiling obj/gameswflib/gameswf_as_classes/as_class.o...
Compiling obj/gameswflib/gameswf_as_classes/as_color.o...
Compiling obj/gameswflib/gameswf_as_classes/as_color_transform.o...
Compiling obj/gameswflib/gameswf_as_classes/as_date.o...
Compiling obj/gameswflib/gameswf_as_classes/as_event.o...
Compiling obj/gameswflib/gameswf_as_classes/as_flash.o...
Compiling obj/gameswflib/gameswf_as_classes/as_geom.o...
Compiling obj/gameswflib/gameswf_as_classes/as_global.o...
Compiling obj/gameswflib/gameswf_as_classes/as_key.o...
Compiling obj/gameswflib/gameswf_as_classes/as_loadvars.o...
Compiling obj/gameswflib/gameswf_as_classes/as_math.o...
Compiling obj/gameswflib/gameswf_as_classes/as_matrix.o...
Compiling obj/gameswflib/gameswf_as_classes/as_mcloader.o...
Compiling obj/gameswflib/gameswf_as_classes/as_mouse.o...
Compiling obj/gameswflib/gameswf_as_classes/as_mouse_event.o...
Compiling obj/gameswflib/gameswf_as_classes/as_netconnection.o...
Compiling obj/gameswflib/gameswf_as_classes/as_netstream.o...
Compiling obj/gameswflib/gameswf_as_classes/as_number.o...
Compiling obj/gameswflib/gameswf_as_classes/as_point.o...
Compiling obj/gameswflib/gameswf_as_classes/as_selection.o...
Compiling obj/gameswflib/gameswf_as_classes/as_sharedobject.o...
Compiling obj/gameswflib/gameswf_as_classes/as_sound.o...
Compiling obj/gameswflib/gameswf_as_classes/as_string.o...
Compiling obj/gameswflib/gameswf_as_classes/as_textformat.o...
Compiling obj/gameswflib/gameswf_as_classes/as_transform.o...
Compiling obj/gameswflib/gameswf_as_classes/as_xml.o...
Compiling obj/gameswflib/gameswf_as_classes/as_xmlsocket.o...
Compiling obj/gameswflib/gameswf_abc.o...
Compiling obj/gameswflib/gameswf_action.o...
Compiling obj/gameswflib/gameswf_avm2.o...
Compiling obj/gameswflib/gameswf_as_sprite.o...
Compiling obj/gameswflib/gameswf_button.o...
Compiling obj/gameswflib/gameswf_canvas.o...
Compiling obj/gameswflib/gameswf_character.o...
Compiling obj/gameswflib/gameswf_disasm.o...
Compiling obj/gameswflib/gameswf_dlist.o...
Compiling obj/gameswflib/gameswf_environment.o...
Compiling obj/gameswflib/gameswf_filters.o...
Compiling obj/gameswflib/gameswf_font.o...
Compiling obj/gameswflib/gameswf_function.o...
Compiling obj/gameswflib/gameswf_impl.o...
Compiling obj/gameswflib/gameswf_listener.o...
Compiling obj/gameswflib/gameswf_log.o...
Compiling obj/gameswflib/gameswf_morph2.o...
Compiling obj/gameswflib/gameswf_movie_def.o...
Compiling obj/gameswflib/gameswf_object.o...
Compiling obj/gameswflib/gameswf_player.o...
Compiling obj/gameswflib/gameswf_render.o...
Compiling obj/gameswflib/gameswf_root.o...
Compiling obj/gameswflib/gameswf_shape.o...
Compiling obj/gameswflib/gameswf_sound.o...
Compiling obj/gameswflib/gameswf_sprite.o...
Compiling obj/gameswflib/gameswf_sprite_def.o...
Compiling obj/gameswflib/gameswf_stream.o...
Compiling obj/gameswflib/gameswf_styles.o...
Compiling obj/gameswflib/gameswf_tesselate.o...
Compiling obj/gameswflib/gameswf_text.o...
Compiling obj/gameswflib/gameswf_tools.o...
Compiling obj/gameswflib/gameswf_types.o...
Compiling obj/gameswflib/gameswf_value.o...
Compiling obj/gameswflib/gameswf_video_impl.o...
Compiling obj/gameswflib/gameswf_mutex.o...
Compiling obj/gameswflib/gameswf_sound_handler_openal.o...
Compiling obj/gameswflib/gameswf_freetype.o...
Compiling obj/gameswflib/gameswf_render_handler_ogl.o...
Archiving obj/libgameswf.a...
Compiling obj/audiolib/ALCheck.o...
Compiling obj/audiolib/AudioDevice.o...
Compiling obj/audiolib/Listener.o...
Compiling obj/audiolib/SoundSource.o...
Compiling obj/audiolib/SoundStream.o...
Archiving obj/libaudio.a...
Creating executable: attract

was wondering if there is a fix for these warnings and what they relate to, i was getting errors relating to ffmpeg and fixed these using the jessie issue post. thx.

**Comment by mickelson** [comment] 2018-08-14 06:38
warnings are known issue. Closing this as a duplicate of issue #383

**Closed by mickelson** 2018-08-14 06:38 UTC
