### ISSUE TITLE
Attract Mode won't remember last ROM played.

### ISSUE THREAD

**Issue by tekn0x** [mickelson/attract#312] opened 2017-02-27 06:38 UTC
Hello. I just updated to the latest commit as of today. Im on a Pi3. I did the update because attract mode would never remember what display wheel or ROM I last used. I would go into a system, and as soon as I backed out it would default back to the bottom of my display menu list. 

The newest update seems to of fixed this, but it still won't remember my last played ROM for a system after I reboot. It's like each system's last played ROM is hard coded somewhere and I can't change it. Example: If I go into sega genesis, the last played ROM is always "rise of the robots" no matter what I do.

**Comment by joyrider3774** [comment] 2017-02-28 18:10
what happens if you exit attract and then reboot manually ? You probably have a shutdown shortcut somewhere inside the attract menu itselve right, could be it's not saving it because your reboot / shutdown while attract is still running. At least with me when i don't reboot it seems to remember it going when going back to the system. so could be that is the cause, might be worth testing it or testing with exiting attract and the restarting attract without a reboot and see if it remembers it

**Comment by tekn0x** [comment] 2017-03-03 22:40
@joyrider3774 You are exactly right. This solved the issue. Thank you for pointing that out. 

Any suggestions on how to add a proper shutdown command to a script? As it stands I have added "sudo shutdown -P now" to the attract mode shutdown command, but I would like to use my menu scripts if possible.

**Comment by joyrider3774** [comment] 2017-03-04 11:25
unfortunatly i don't know of a way to counteract this. I tried using killall attract but it does not work probably because attract does not save the positions when it recives the SIGTERM signal. I'm not even sure how it handles SIGTERM. If it would do handle SIGTERM in the same way as exiting normally it could be possible to use kill or killall to send SIGTERM before the shutdown but currently this does not work. Also i did not test if the script keeps running when sending SIGTERM only tested sending SIGTERM using killall from ssh and saw the it did not save the positions.

PS. if you exit attract and restart it does attract position itselve on the last system you used ? it doesn't seem to do that with me (well it positions somewhere but not last system used) but it does remember last played games for a system then

**Comment by tekn0x** [comment] 2017-03-07 17:42
Something strange is happening. When I wrote my last reply, it was remembering roms after a shutdown exit command. Now it is not for some reason. Very odd.

PS. It does not. It starts on the same system for me every time.

**Comment by ctmay4** [comment] 2017-04-22 14:20
I have the same problem because more often than not the cabinet gets shut off by pulling the plug.  Would it be possible to save that last game played when it is launched instead of only when attract mode is exited?

**Comment by Enverex** [comment] 2017-06-18 19:22
I agree with @ctmay4 for other reasons. Any chance this could be implemented?

**Comment by Enverex** [comment] 2017-06-25 16:35
Ok, I've tried to do this myself. I've tested it and it seems to work fine. Request is here https://github.com/mickelson/attract/pull/362

**Comment by Enverex** [comment] 2017-06-25 20:28
Mickelson's merged this in now, so update you your problem should be fixed.

@mickelson you should be able to close this now but it may be worth waiting for at least one confirmation first, up to you.

**Comment by tekn0x** [comment] 2017-06-25 20:29
How has this been resolved, what's the current solution?  Also thank you
so much to whoever helped complete this.

**Comment by Enverex** [comment] 2017-06-25 20:44
I wrote a minor change that has AttractMode save your current lists (like it does when you exit AttractMode properly) but it does this each time you launch a game, so shutting down your machine without exiting AM properly won't reset your lists every time now.

**Comment by tekn0x** [comment] 2017-06-25 21:09
That sounds like an excellent solution. Thank you so much.

**Comment by tekn0x** [comment] 2017-07-04 18:47
I can confirm this fix is now working. Thank you.

**Comment by Enverex** [comment] 2017-07-04 19:16
Huzzah, enjoy guys (amazed it was that simple).

**Closed** 2018-08-14 05:45 UTC
