### ISSUE TITLE
obj/fe_blend.o fails to compile

### ISSUE THREAD

**Issue by fanfani** [mickelson/attract#446] opened 2018-05-31 07:57 UTC
hello there,

i am having issues compiling attractmode from latest git (relevant compiler output below)
i'm running debian jessie, and did not have any issues compiling from source until recently.

```
Compiling obj/fe_blend.o...
src/fe_blend.cpp: In static member function ‘static sf::BlendMode FeBlend::get_blend_mode(int)’:
src/fe_blend.cpp:35:76: error: expression list treated as compound expression in functional cast [-fpermissive]
    return sf::BlendMode(sf::BlendMode::One, sf::BlendMode::OneMinusSrcColor);
                                                                            ^
src/fe_blend.cpp:35:24: error: expected primary-expression before ‘(’ token
    return sf::BlendMode(sf::BlendMode::One, sf::BlendMode::OneMinusSrcColor);
                        ^
src/fe_blend.cpp:35:29: error: ‘sf::BlendMode’ is not a class or namespace
    return sf::BlendMode(sf::BlendMode::One, sf::BlendMode::OneMinusSrcColor);
                             ^
src/fe_blend.cpp:35:49: error: ‘sf::BlendMode’ is not a class or namespace
    return sf::BlendMode(sf::BlendMode::One, sf::BlendMode::OneMinusSrcColor);
                                                 ^
src/fe_blend.cpp:37:81: error: expression list treated as compound expression in functional cast [-fpermissive]
    return sf::BlendMode(sf::BlendMode::DstColor, sf::BlendMode::OneMinusSrcAlpha);
                                                                                 ^
src/fe_blend.cpp:37:24: error: expected primary-expression before ‘(’ token
    return sf::BlendMode(sf::BlendMode::DstColor, sf::BlendMode::OneMinusSrcAlpha);
                        ^
src/fe_blend.cpp:37:29: error: ‘sf::BlendMode’ is not a class or namespace
    return sf::BlendMode(sf::BlendMode::DstColor, sf::BlendMode::OneMinusSrcAlpha);
                             ^
src/fe_blend.cpp:37:54: error: ‘sf::BlendMode’ is not a class or namespace
    return sf::BlendMode(sf::BlendMode::DstColor, sf::BlendMode::OneMinusSrcAlpha);
                                                      ^
src/fe_blend.cpp:39:73: error: expression list treated as compound expression in functional cast [-fpermissive]
    return sf::BlendMode(sf::BlendMode::DstColor, sf::BlendMode::SrcColor);
                                                                         ^
src/fe_blend.cpp:39:24: error: expected primary-expression before ‘(’ token
    return sf::BlendMode(sf::BlendMode::DstColor, sf::BlendMode::SrcColor);
                        ^
src/fe_blend.cpp:39:29: error: ‘sf::BlendMode’ is not a class or namespace
    return sf::BlendMode(sf::BlendMode::DstColor, sf::BlendMode::SrcColor);
                             ^
src/fe_blend.cpp:39:54: error: ‘sf::BlendMode’ is not a class or namespace
    return sf::BlendMode(sf::BlendMode::DstColor, sf::BlendMode::SrcColor);
                                                      ^
src/fe_blend.cpp:41:76: error: expression list treated as compound expression in functional cast [-fpermissive]
    return sf::BlendMode(sf::BlendMode::One, sf::BlendMode::OneMinusSrcAlpha);
                                                                            ^
src/fe_blend.cpp:41:24: error: expected primary-expression before ‘(’ token
    return sf::BlendMode(sf::BlendMode::One, sf::BlendMode::OneMinusSrcAlpha);
                        ^
src/fe_blend.cpp:41:29: error: ‘sf::BlendMode’ is not a class or namespace
    return sf::BlendMode(sf::BlendMode::One, sf::BlendMode::OneMinusSrcAlpha);
                             ^
src/fe_blend.cpp:41:49: error: ‘sf::BlendMode’ is not a class or namespace
    return sf::BlendMode(sf::BlendMode::One, sf::BlendMode::OneMinusSrcAlpha);
                                                 ^
Makefile:456: set di istruzioni per l'obiettivo "obj/fe_blend.o" non riuscito
make: *** [obj/fe_blend.o] Errore 1
```

ciao!

**Comment by oomek** [comment] 2018-05-31 21:52
Have you tried compiling with full clean?

**Comment by fanfani** [comment] 2018-05-31 21:57
do you mean did i run `make clean` before `make`? yes i did

**Comment by oomek** [comment] 2018-05-31 22:03
Could you try my fork with the recent fixes and tell if the issue is also there ?
https://github.com/oomek/attract/tree/fixes

**Comment by fanfani** [comment] 2018-05-31 22:07
just run:

```
$ git clone https://github.com/oomek/attract.git

$ cd attract

$ make

```
same result

**Comment by oomek** [comment] 2018-05-31 22:43
What SFML version do you have there?

**Comment by fanfani** [comment] 2018-06-01 12:07
```
$ aptitude versions libsfml-dev
Package libsfml-dev:                        
i   2.1+dfsg2-1+b1    stable    500 
```

**Comment by mickelson** [comment] 2018-06-01 16:44
Attractmode is meant to work on any sfml 2.x version.  I didn’t realize blendmode was only added with sfml 2.3 when this was merged.  This is a bug in Attractmode that will get fixed when I am able to work on it again (in about 3 weeks)... thanks for reporting this

**Comment by oomek** [comment] 2018-06-01 17:08
Actually to be precise it’s about constructing custom blend modes which I used for non standard blending. The standard blending modes were present in earlier sfml versions

**Comment by oomek** [comment] 2018-06-01 17:10
What do you do in that kind of situations?

**Comment by oomek** [comment] 2018-06-03 08:11
Andrew, would you please explain to me what is the reason of keeping the compatibility with the old SFML libraries?

**Comment by mickelson** [comment] 2018-06-04 14:34
Well the main reason is that the compile instructions in compile.md state that any 2.x version of SFML is what is needed to compile.

Beyond that, I want it to be as backwards compatible as possible (within reason) because there are many reasons why people may not be able to use the most recent sfml  (Debian and some other linux distros don’t get released that often, etc.).

**Comment by mickelson** [comment] 2018-06-30 19:52
Hi there, I'm unable to reproduce this here but some changes have been made that might fix this.  Could you try compiling again with the latest code from master and let me know if it fixes this? thanks

**Comment by oomek** [comment] 2018-07-02 07:36
Calling BlendMode constructor will fail on older SFML versions. Some additional checks for the SFML versions will be required or just simple try catch block.

**Comment by mickelson** [comment] 2018-07-03 00:38
ok i think I've got it now, could you try updating and compiling again??

**Comment by fanfani** [comment] 2018-07-03 07:08
it works! thank you :-)

**Closed** 2018-07-06 04:00 UTC
